### ISSUE TITLE
I think this is broken

### ISSUE THREAD

**Issue by JohnJohnMohn** [CallyHam/Google-Top-Bar#1]
Everytime i try to install it ends up looking like this mess 
![image](https://github.com/CallyHam/Google-Top-Bar/assets/96588320/482a00a1-997e-4e01-9466-a4e6720468be)

**Comment by CallyHam** [comment]
it looks like you need to install [classic-top-bar.user.css](https://github.com/CallyHam/Google-Top-Bar/blob/main/classic-top-bar.user.css) into a userstyle manager such as [stylus](https://github.com/openstyles/stylus), chances are though that some things will still be broken since google is pretty annoying to work with for userstyles

**Comment by JohnJohnMohn** [comment]
> it looks like you need to install [classic-top-bar.user.css](https://github.com/CallyHam/Google-Top-Bar/blob/main/classic-top-bar.user.css) into a userstyle manager such as [stylus](https://github.com/openstyles/stylus), chances are though that some things will still be broken since google is pretty annoying to work with for userstyles

Okay, i see now, you needed to install both files, thanks.
